<?php

namespace App\Service;

class FilterService{
    public $Years=[
        ['A',1980,2010],
        ['B',1981,2011],
        ['C',1982,2012],
        ['D',1983,2013],
        ['E',1984,2014],
        ['F',1985,2015],
        ['G',1986,2016],
        ['H',1987,2017],
        ['J',1988,2018],
        ['K',1989,2019],
        ['L',1990,2020],
        ['M',1991,2021],
        ['N',1992,2022],
        ['P',1993,2023],
        ['R',1994,2024],
        ['S',1995,2025],
        ['T',1996,2026],
        ['V',1997,2027],
        ['W',1998,2028],
        ['X',1999,2029],
        ['Y',2000,2030],
        ['1',2001,2031],
        ['2',2002,2032],
        ['3',2003,2033],
        ['4',2004,2034],
        ['5',2005,2035],
        ['6',2006,2036],
        ['7',2007,2037],
        ['8',2008,2038],
        ['9',2009,2039]
    ];

    public $Regions=[
        ["/^[A-C]+$/","Africa"],
        ["/^[J-R]+$/",'Asia'],
        ["/^[S-Z]+$/",'Europe'],
        ["/^[1-5]+$/",'North America'],
        ["/^[6-7]+$/",'Oceania'],
        ["/^[8-9]+$/",'South America']];
    public $Countries=[
        ['/1[A-Z0-9]/','United States'],
        ['/2[A-Z0-9]/','Canada'],
        ['/3[8-90]/','not assigned'],
        ['/3[A-W]/','Mexico'],
        ['/3[X-Z1-7]/','Costa Rica'],
        ['/4[A-Z0-9]/','United States'],
        ['/5[A-Z0-9]/','United States'],
        ['/6[A-W]/','Australia'],
        ['/6[X-Z0-9]/','not assigned'],
        ['/7[A-E]/','New Zealand'],
        ['/7[F-Z0-9]/','not assigned'],
        ['/8[3-90]/','not assigned'],
        ['/8[A-E]/','Argentina'],
        ['/8[F-K]/','Chile'],
        ['/8[L-R]/','Ecuador'],
        ['/8[S-W]/','Peru'],
        ['/8[X-Z1-2]/','Venezuela'],
        ['/9[3-9]/','Brazil'],
        ['/9[A-E]/','Brazil'],
        ['/9[F-K]/','Colombia'],
        ['/9[L-R]/','Paraguay'],
        ['/9[S-W]/','Uruguay'],
        ['/9[X-Z1-2]/','Trinidad & Tobago'],
        ['/A[A-H]/','South Africa'],
        ['/A[J-N]/','Ivory Coast'],
        ['/A[P-Z0-9]/','not assigned'],
        ['/B[A-E]/','Angola'],
        ['/B[F-K]/','Kenya'],
        ['/B[L-R]/','Tanzania'],
        ['/B[S-Z0-9]/','not assigned'],
        ['/C[A-E]/','Benin'],
        ['/C[F-K]/','Malagasy'],
        ['/C[L-R]/','Tunisia'],
        ['/C[S-Z0-9]/','not assigned'],
        ['/D[A-E]/','Egypt'],
        ['/D[F-K]/','Morocco'],
        ['/D[L-R]/','Zambia'],
        ['/D[S-Z0-9]/','not assigned'],
        ['/E[A-E]/','Ethiopia'],
        ['/E[F-K]/','Mozambique'],
        ['/E[L-Z0-9]/','not assigned'],
        ['/F[A-E]/','Ghana'],
        ['/F[F-K]/','Nigeria'],
        ['/F[F-K]/','Madagascar'],
        ['/F[L-Z0-9]/','not assigned'],
        ['/G[A-Z0-9]/','not assigned'],
        ['/H[A-Z0-9]/','not assigned'],
        ['/J[A-Z0-9]/','Japan'],
        ['/K[A-E]/','Sri Lanka'],
        ['/K[F-K]/','Israel'],
        ['/K[L-R]/','Korea (South)'],
        ['/K[S-Z0-9]/','not assigned'],
        ['/L[A-Z0-9]/','China'],
        ['/M[A-E]/','India'],
        ['/M[F-K]/','Indonesia'],
        ['/M[L-R]/','Thailand'],
        ['/M[S-Z0-9]/','not assigned'],
        ['/N[F-K]/','Pakistan'],
        ['/N[L-R]/','Turkey'],
        ['/N[S-Z0-9]/','not assigned'],
        ['/P[A-E]/','Philipines'],
        ['/P[F-K]/','Singapore'],
        ['/P[L-R]/','Malaysia'],
        ['/P[S-Z0-9]/','not assigned'],
        ['/R[A-E]/','United Arab Emirates'],
        ['/R[F-K]/','Taiwan'],
        ['/R[L-R]/','Vietnam'],
        ['/R[S-Z0-9]/','not assigned'],
        ['/S[0-9]/','not assigned'],
        ['/S[A-M]/','Great Britain'],
        ['/S[N-T]/','Germany'],
        ['/S[U-Z]/','Poland'],
        ['/T[2-90]/','not assigned'],
        ['/T[A-H]/','Switzerland'],
        ['/T[J-P]/','Czechoslovakia'],
        ['/T[R-V]/','Hungary'],
        ['/T[W-Z1]/','Portugal'],
        ['/U[1-4]/','not assigned'],
        ['/U[5-7]/','Slovakia'],
        ['/U[8-90]/','not assigned'],
        ['/U[A-G]/','not assigned'],
        ['/U[H-M]/','Denmark'],
        ['/U[N-T]/','Ireland'],
        ['/U[U-Z]/','Romania'],
        ['/V[3-5]/','Croatia'],
        ['/V[6-90]/','Estonia'],
        ['/V[A-E]/','Austria'],
        ['/V[F-R]/','France'],
        ['/V[S-W]/','Spain'],
        ['/V[X-Z1-2]/','Yugoslavia'],
        ['/W[A-Z0-9]/','Germany'],
        ['/X[3-90]/','Russia'],
        ['/X[A-E]/','Bulgaria'],
        ['/X[F-K]/','Greece'],
        ['/X[L-R]/','Netherlands'],
        ['/X[S-W]/','U.S.S.R.'],
        ['/X[X-Z1-2]/','Luxembourg'],
        ['/Y[3-5]/','Belarus'],
        ['/Y[6-90]/','Ukraine'],
        ['/Y[A-E]/','Belgium'],
        ['/Y[F-K]/','Finland'],
        ['/Y[L-R]/','Malta'],
        ['/Y[S-W]/','Sweden'],
        ['/Y[X-Z1-2]/','Norway'],
        ['/Z[3-5]/','Lithuania'],
        ['/Z[6-90]/','not assigned'],
        ['/Z[A-R]/','Italy'],
        ['/Z[S-W]/','not assigned'],
        ['/Z[X-Z1-2]/','Slovenia'],
        ['/90/','Not ussigned']
        ];
}